### ISSUE TITLE
Trophy case update problem with private git repo

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#170]
https://github.com/robiningelbrecht/strava-activities-template/blob/f738049b97915f260158f44cf7cf23aa9c9f8f91/src/Domain/Strava/Strava.php#L217

At this line the code retrieves the master challenge file to update, but my repo is private so this fails.  But as the workflow pulls everything from the git repo, isn't is feasible to use the filesystem file?

**Comment by robiningelbrecht** [comment]
Yes, in this case this is possible indeed, but you'll have the same issue for photos and challenge icons and there we do want to use the remote URI. The reason for doing so is that I don't want to host all images for the HTML version with my own hosting provider (I use a free tier). This would result in me having to pay for hosting :)

**Comment by pdoteter** [comment]
Good to know about the photos and challenges, will keep the repo private for a while to see how things work out, as I already have a public strava profile, making this repo public is not a problem.  But in the beginning I want to test first...
