### ISSUE TITLE
Deleted activities

### ISSUE THREAD

**Issue by mdleye** [robiningelbrecht/strava-activities-template#187]
Namiddagrit is gesynced, maar later verwijderd van Strava wegens gemerged in 1 file voor GranFondo op de rollen

![image](https://github.com/robiningelbrecht/strava-activities-template/assets/149835529/d24faa36-5efa-401a-aae5-46a127fd9274)

**Comment by robiningelbrecht** [comment]
@mdleye fixed. This activity should be removed on the next "update run"
