### ISSUE TITLE
Error with downloading PNG images  during Import Challenges

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#197]
I get this error:

Could not import "July Cycling Challenge", error: cURL error 61: Unrecognized content encoding type. libcurl understands deflate, gzip, br, zstd content encodings. (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://dgalywyr863hv.cloudfront.net/challenges/2476/2476-logo-100.png

**Comment by robiningelbrecht** [comment]
@pdoteter That's something I can't fix, it is an error on Strava's end. 
This error should not crash the import though, just skip the fault image

**Comment by pdoteter** [comment]
Indeed, for me it's ok just wanted to signal the occurrence

**Comment by robiningelbrecht** [comment]
Closing this one, as I can't do anything to properly fix this
