### ISSUE TITLE
During generation Building HTML, a breaking exception something map related

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#198]
In LeafletMap.php line 147:
                                                                           
  No map found for starting coordinate [37.202782183886,-112.98765518703]  
                                                                           

app:strava:build-files

**Comment by robiningelbrecht** [comment]
@pdoteter Hmm this is probably a virtual activity. Currently the code assumes all virtual activities are Zwift activities. Do you have other virtual ones?

**Comment by pdoteter** [comment]
Yes Rouvy:
https://www.strava.com/activities/10425665938

And I think BKool in the past too, the error doesn't state which activity

**Comment by robiningelbrecht** [comment]
@pdoteter Hmm Ok, this is an actual bug. I need to change the code and not assume every virtual activity is a zZwift one :)
Error occurs when trying to render a Zwift map, but the coordinates do not fit an actual Zwift region:
<img width="596" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/0fc6eedb-83c1-4789-b9ac-1abd26e4d95b">

**Comment by pdoteter** [comment]
Ok, glad to help 😄, I have a big data set, eventually everything will work

**Comment by robiningelbrecht** [comment]
@pdoteter Are you ok with me mentioning you in the "release notes" on the readme of this repository?

**Comment by pdoteter** [comment]
No problem with that

**Comment by robiningelbrecht** [comment]
@pdoteter You can give it another try after updating the template
