### ISSUE TITLE
Importing segments and efforts. argument error

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#202]
Importing segments and efforts...
App\Infrastructure\ValueObject\String\Identifier::fromUnprefixed(): Argument #1 ($unprefixed) must be of type string, int given, called in /home/runner/work/Strava-activity/Strava-activity/src/Domain/Strava/Segment/ImportSegments/ImportSegmentsCommandHandler.php on line 53
Error: Process completed with exit code 1.

**Comment by robiningelbrecht** [comment]
@pdoteter Should be fixed after updating the template

**Comment by pdoteter** [comment]
Fixed, it's generating the html at this moment

**Comment by robiningelbrecht** [comment]
🥳 Let's hope the script successfully runs now!

**Comment by robiningelbrecht** [comment]
@pdoteter sent you a message on CC forum
