### ISSUE TITLE
Segment View - Add pagination (automatic or manual?)

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#215]
I have a lot of segments 😄 , it takes about 5 seconds to load.  Looking at the search functionality it's all loaded client side (off course it's a static site ...
Don't know if it possible.

**Comment by robiningelbrecht** [comment]
I think paging and searching combined is hard to achieve when the site is static indeed. I'll give it a try

**Comment by robiningelbrecht** [comment]
@pdoteter problem is, if I add pagination, search won't work properly anymore because only the rows that are loaded will be searched. Not sure how to proceed here. Suggestions?

**Comment by pdoteter** [comment]
This is a difficult one, I checked my stats and see a lot of segments in that view. When filtering in the search bar, the browser (chrome) really struggles. Typing P (1 sec), typing PA 5 seconds waiting.  And that window use 2 Gb memory.
So I rather go for paging, but in the end if all snapshots are loaded the same problem exists.

**Comment by robiningelbrecht** [comment]
Use ajax calls to search? https://www.florin-pop.com/blog/2019/06/vanilla-javascript-instant-search/
Or store all data in localStorage and use localStorage...

**Comment by pdoteter** [comment]
I'm not really a reference when it comes to frontend-developing, the last we had such a problem we had to adapt the angular front-end and back-end to be efficient.
I think now we use a lot of localStorage in our frontends, so maybe that's the way to go, I think the memory is the least of the concern on this page, the slowness certainly comes from the html rendering

**Comment by robiningelbrecht** [comment]
I'll re-visit this issue later. For this to work I would need to drop the static page rendering which I don't want to do right now

**Comment by robiningelbrecht** [comment]
@pdoteter it's searching that is really slow right? Maybe I can add an "Min char" to the search and set it to 3. That way the search only will kick in when at least 3 characters are in the search input...

**Comment by pdoteter** [comment]
Search is doable, just the whole page is slow on the first rendering. The min char to 3 is a good idea

**Comment by robiningelbrecht** [comment]
Investigate https://github.com/fiduswriter/Simple-DataTables

**Comment by pdoteter** [comment]
> Investigate https://github.com/fiduswriter/Simple-DataTables

Looks promising, tried the demo, added 6000 rows and view 10000 rows and it was fast enough.Clicking sorting and all that was fast enough

**Comment by robiningelbrecht** [comment]
https://github.com/NeXTs/Clusterize.js/issues?q=sort

**Comment by pdoteter** [comment]
That Clusterize works fast, don't see a possibility on search/sorting with it

**Comment by robiningelbrecht** [comment]
@pdoteter I completely refactored the activity and segments overview. Should be way faster in loading, sorting and searching. Can you confirm?

**Comment by pdoteter** [comment]
Top, works like a charm now
