### ISSUE TITLE
Segment View - Add columns

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#216]
Due to the huge list of segments, most of the time the segment names doesn't ring a bell.  But I have starred all my favorite segments, so add a column with Starred (to be sort or filter on)

Another column missing for me: times ridden

**Comment by robiningelbrecht** [comment]
@pdoteter Name of the segment will contain a star now: 
<img width="505" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/941858bc-4181-4ba3-817f-6d885ca0dd2a">

You can also search on "Starred" or "Favourite" to filter on all your starred segments
