### ISSUE TITLE
Activity view - Link to Strava - extra icon open in new tab

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#217]
add "open in new tab" next to the Strava activity link ( I know you're probably not a fan that the link gets standard opened in a new tab)
But if it's opened from the segment detail view, and you back the history is lost from where you left.

**Comment by pdoteter** [comment]
The same goes if you have sorted in the Activity overview

**Comment by robiningelbrecht** [comment]
@pdoteter Not sure where you would want this extra link. Can you provide a screenshot please?

**Comment by pdoteter** [comment]
![image](https://github.com/robiningelbrecht/strava-activities-template/assets/16332883/9f2afea3-4f14-4844-ad42-76f43a0a0b3c)
There, with an icon like this:
https://www.flaticon.com/free-icons/new-tab

**Comment by robiningelbrecht** [comment]
Ok, Adding a target=_blank to that external link is fine with me. I assumed you wanted it on some internal link. That I won't do ;)

**Comment by pdoteter** [comment]
No indeed not on internal links I agree there
