### ISSUE TITLE
Top Right corner - shows your profile links

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#218]
I have certainly no problem with your credentials on the page, for sure. I'm happy you took the time to write this.  But now it seems the statistics page is of you.  I don't see any links to the profile of the owner

**Comment by robiningelbrecht** [comment]
@pdoteter I'll make sure it's clear that those credentials are of the creator of the project.
I'll add a link to the strava profile of the "user" at the bottom of the sidebar

**Comment by robiningelbrecht** [comment]
@pdoteter Has been added:
<img width="233" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/f92d048f-90e0-4837-b697-a73becb85846">
