### ISSUE TITLE
Window views (I hope you understand what I mean)

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#220]
![window-drag](https://github.com/robiningelbrecht/strava-activities-template/assets/16332883/4c2665bd-8486-4fed-8c94-8a00df5a81ae)
Added an attachment to the part what I mean.

When hovering over the begin or endpoint, changes the cursor and you think you're able to expand/contract the range, but it goes into drag mode.
Also after selecting a larger range and wanting to drag that, it changes the period to the default one.

It's in all those little drag windows I found

**Comment by robiningelbrecht** [comment]
Yes, that's by design. The drag windows have a fixed range to make sure the chart is displayed correctly on all screen sizes
