### ISSUE TITLE
Last refresh data

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#229]
What I'm missing in the HTML and markdown output is a date/time of the last refresh.  Always handy to see when the update has ran

**Comment by robiningelbrecht** [comment]
@pdoteter I added the last update date at the bottom of the sidebar in the HTML version:
<img width="244" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/6f5963a3-be09-413a-851d-63e14f9002d4">

I did not add it to the markdown version as you can easily see the last commit update at the top of the page
