### ISSUE TITLE
Warning during generation (a lot of them 😄 )

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#260]
PHP Warning:  array_count_values(): Can only count string and integer values, entry skipped in /home/runner/work/Strava-activity/Strava-activity/src/Domain/Strava/Activity/Stream/ReadModel/StreamBasedActivityPowerRepository.php on line 85

**Comment by robiningelbrecht** [comment]
@pdoteter For which activities do these occur? Can't reproduce with my own activities
