### ISSUE TITLE
Build failed Address::getState() must be string

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#282]
Building HTML...
PHP Warning:  Undefined array key "state" in /home/runner/work/Strava-activity/Strava-activity/src/Domain/Nominatim/Address.php on line 32
App\Domain\Nominatim\Address::getState(): Return value must be of type string, null returned
Error: Process completed with exit code 1.

**Comment by robiningelbrecht** [comment]
@pdoteter Should be fixed
