### ISSUE TITLE
Heatmap doesn't take into account the privacy zone from Strava

### ISSUE THREAD

**Issue by pdoteter** [robiningelbrecht/strava-activities-template#291]
I checked the individual tracks and they take into account the privacy zone, but in the heatmap I see that tracks are drawn in the zone:

Strava:
![image](https://github.com/robiningelbrecht/strava-activities-template/assets/16332883/14e8558a-7e94-4270-a9a6-58121d384eb8)

I don't know how it works, but I think it's related to old activities, that pass through the now active privacy zone.  I moved in 2013, and changed my privacy zone than.  But I had routes from before that went through that privacy zone.

Not a real issue for me, because the routes doesn't reveal anything.

**Comment by robiningelbrecht** [comment]
I just display what Strava gives me, so I don't think I can do much here...

**Comment by pdoteter** [comment]
Ok, no problem as said nothing important for me, just wanted to point out, closing issue
