### ISSUE TITLE
5 days later, still hasnt completed 'Update strava activities' workflow

### ISSUE THREAD

**Issue by dylix** [robiningelbrecht/strava-activities-template#311]
I have ~2200 activities, so I would expect it to take a day or two or three, however it seems to be redownloading the same ones over and over.

**Comment by robiningelbrecht** [comment]
Hi @dylix ,

I just checked your repository and I can see that there's an issue while importing segments:
<img width="762" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/77b28416-57e8-4e81-b5c1-cd5ae43ec558">

Apparently not al segments ids are unique, and they should be. I'll need to look into this and fix this.
Thanks for the bug report!

**Comment by robiningelbrecht** [comment]
@dylix issue should be fixed. In the next couple of days all your activities should be imported.
You can keep an eye on the actions, they should not fail anymore: https://github.com/dylix/strava-activities-template/actions

**Comment by dylix** [comment]
@robiningelbrecht 
Are they failing now in a way that is intended?
Has failed the last two days..

https://github.com/dylix/strava-activities-template/actions/runs/7574524166
https://github.com/dylix/strava-activities-template/actions/runs/7560308336

`=> Imported activity "Morning Ride"
  => Imported activity "Afternoon Ride"
  => Imported activity "Morning Ride"
  => Imported activity "Afternoon Ride"
  => Imported activity "Morning Ride"
  => Imported activity "Afternoon Ride"

In RequestException.php line 113:
                                                                               
  Server error: `GET [https://www.strava.com/api/v3/activities/2100058002`](https://www.strava.com/api/v3/activities/2100058002%60) res  
  ulted in a `502 Bad Gateway` response:                                       
  <!DOCTYPE html>                                                              
  <html>                                                                       
  <head>                                                                       
    <title>Strava is temporarily unavailable</title>                           
    <meta http-equiv='Content-Type' conte (truncated...)                       
                                                                               

app:strava:import-data

Error: Process completed with exit code 255.`

**Comment by robiningelbrecht** [comment]
@dylix no, the erro`resulted in a 502 Bad Gateway response:` is Strava that made a booboo :).
Their server crashed, which causes your import to crash as well. 

I'll open a new improvement ticket (and tag you) to make sure, if this happens, the process does not crash but just stops and continues the next day.

Sorry for the inconvenience!

**Comment by robiningelbrecht** [comment]
@dylix I noticed your actions still fail. I debugged this and noticed I forgot something. This PR should fix this: https://github.com/robiningelbrecht/strava-activities-template/pull/327

Let's hope that tonight your activities get imported :)
