### ISSUE TITLE
Make sure import process does not crash when Strava bails out

### ISSUE THREAD

**Issue by robiningelbrecht** [robiningelbrecht/strava-activities-template#318]
https://github.com/dylix/strava-activities-template/actions/runs/7574524166
https://github.com/dylix/strava-activities-template/actions/runs/7560308336

Handle 500 errors as well, next to 429 error "too many requests"

cc @dylix

**Comment by dylix** [comment]
also ran into this.. https://github.com/dylix/strava-activities-template/actions/runs/7587844275

**Comment by robiningelbrecht** [comment]
@dylix that's because GitHub terminates jobs after 6 hours. Another issue to fix. I'll keep you up to date

**Comment by robiningelbrecht** [comment]
@dylix I fixed the Strava server errors. When that happens, the process will stop and continue the next day. Still need to fix the job termination after 6 hours though

**Comment by robiningelbrecht** [comment]
@dylix Just finished implementing a fix for the 6 hour job limit.
Starting from tomorrow, your activities should be imported. Hopefully everything runs smooth now. Thanks for the bug reports!
