### ISSUE TITLE
404 when building HTML version

### ISSUE THREAD

**Issue by dace93** [robiningelbrecht/strava-activities-template#328]
Hello Robin,

I wanted to drop a quick note to say kudos on the awesome project! The documentation is super noob-friendly, which is exactly what I needed.

I'm running into a hiccup, though. When I try to build the app with Vercel, it throws a 404 error. Any ideas on what I might have missed or done wrong?

Also, I couldn't find details on how to actually display the data in the markdown. Can you point me in the right direction?

Thanks for your help!

**Comment by robiningelbrecht** [comment]
Hi @dace93 , thanks for your kind words!

The markdown version will automatically appear on your repository [homepage](https://github.com/dace93/stravastats) when all activities have been imported. If you have a lot, this might take a few days.

In vercel, did you configure your root directory like this?
<img width="617" alt="image" src="https://github.com/robiningelbrecht/strava-activities-template/assets/203894/35e662af-ec30-4e1d-ade2-1d33c0ee6fe6">

**Comment by robiningelbrecht** [comment]
Also, vercel will only start working when all your activities are imported, again, depending on how many you have, this might take a few days...

**Comment by dace93** [comment]
> Hi @dace93 , thanks for your kind words!
> 
> The markdown version will automatically appear on your repository [homepage](https://github.com/dace93/stravastats) when all activities have been imported. If you have a lot, this might take a few days.
> 
> In vercel, did you configure your root directory like this? <img alt="image" width="617" src="https://private-user-images.githubusercontent.com/203894/299069280-35e662af-ec30-4e1d-ade2-1d33c0ee6fe6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzg1NDIsIm5iZiI6MTcwNjAzODI0MiwicGF0aCI6Ii8yMDM4OTQvMjk5MDY5MjgwLTM1ZTY2MmFmLWVjMzAtNGUxZC1hZGUyLTFkMzNjMGVlNmZlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxOTMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYTk5YzcwOWVmM2M0MjA4MmIwNTNmOTIwMzg2NjM0N2U1ZTFkOTQ3ZTJiMGU2YzIyMjFmODY1NDIxMTFlOGZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8Nh-LHwqn-isduQIf8yUqNtK7F68GgMvQhY9flLNAIA">

Yes, I've configured it like in your screenshot.

**Comment by robiningelbrecht** [comment]
@dace93 I'm going to close this issue. Feel free to open new issues when needed
