### ISSUE TITLE
Importing challenges...

### ISSUE THREAD

**Issue by dylix** [robiningelbrecht/strava-activities-template#329]
Hi, it's me again :)

https://github.com/dylix/strava-activities-template/actions/runs/7638668201/job/20810051112

In ExceptionConverter.php line 41:
                                                                               
  An exception occurred while executing a query: SQLSTATE[23000]: Integrity c  
  onstraint violation: 19 UNIQUE constraint failed: Challenge.challengeId      
                                                                               

In Exception.php line 28:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint faile  
  d: Challenge.challengeId                                                     
                                                                               

In Statement.php line 130:
                                                                               
  SQLSTATE[23000]: Integrity constraint violation: 19 UNIQUE constraint faile  
  d: Challenge.challengeId                                                     
                                                                               

app:strava:import-data

Error: Process completed with exit code 19.

**Comment by robiningelbrecht** [comment]
Hi @dylix, thanks again for the bug report!
I'll get to it as soon as I can, somewhat busy atm ;)
I'll keep you up to date

**Comment by robiningelbrecht** [comment]
@dylix This bug should be resolved. Could you try again and let me know?

**Comment by dylix** [comment]
@robiningelbrecht yep, it finally completed! Awesome! Thanks for all your work :)

**Comment by robiningelbrecht** [comment]
@dylix you ride A LOT :), waw.
If you have any feature requests, feel free to open new issues. I'll be glad to add them
