### ISSUE TITLE
Building HTML... - max(): Argument #1 ($value) must contain at least one element

### ISSUE THREAD

**Issue by valexp** [robiningelbrecht/strava-activities-template#332]
Hello Robin,
amazing project!
I'm having a problem running the "Update strava activities" workflow, it stop with this error:

Building HTML...
max(): Argument #1 ($value) must contain at least one element
Error: Process completed with exit code 1.

Thanks for your help!

**Comment by robiningelbrecht** [comment]
Hi @valexp, thanks for your bug report! I'll look into it and let you now when fixed :)

**Comment by robiningelbrecht** [comment]
@valexp do you happen to know if your activities have power data available yes/no?

**Comment by valexp** [comment]
Hi Robin,
my cycling activities don't have power data, my running activities do.

Here the messages from the new run:

Building HTML...
  => Calculating Eddington
  => Calculating activity highlights
  => Calculating weekday stats
  => Calculating daytime stats
  => Calculating monthly stats
  => Calculating best power outputs
  => Enriching activities with data
  => Building index.html
  => Building dashboard.html
max(): Argument #1 ($value) must contain at least one element
Error: Process completed with exit code 1.

Thanks for helping me

**Comment by robiningelbrecht** [comment]
@valexp Can you try again, I think I fixed the bug, not sure :).
