### ISSUE TITLE
Possibility to change the imported activities from type ride to type run?

### ISSUE THREAD

**Issue by txck83** [robiningelbrecht/strava-activities-template#337]
Hello
I really like this statistics tool. Sadly i don't ride often, but run often. Is there a possibility to change the imported activities to type run instead of ride, user based on the own "copied template"?

**Comment by robiningelbrecht** [comment]
@txck83 not without you changing the code.
Currently everything is focussed on bike rides as I, myself do not run. 
So this is not supported and probably never will, unless you do it yourself :)
