### ISSUE TITLE
openstreetmap forbidden

### ISSUE THREAD

**Issue by dylix** [robiningelbrecht/strava-activities-template#338]
the last 4 days, openstreetmap has been blocking access...

In RequestException.php line 113:
                                                                               
  Client error: `GET https://nominatim.openstreetmap.org/reverse?lat=insert_real_lat_here&lon=insert_real_lon_here&format=json` resulted in a `403 Forbidden` res  
  ponse:                                                                       
  <html>                                                                       
  <head>                                                                       
  <title>Access blocked</title>                                                
  </head>                                                                      
  <body>                                                                       
  <h1>Access blocked</h1>                                                      
                                                                               
  <p>You have been blocked because you (truncated...)

**Comment by robiningelbrecht** [comment]
Yeah, the reverse geocoding API blocked the IP of GitHub I think.
Will need to disable it for now, everything should be fixed by the next run

**Comment by dylix** [comment]
> Yeah, the reverse geocoding API blocked the IP of GitHub I think. Will need to disable it for now, everything should be fixed by the next run

Awesome! I was worried this project had been abandoned 😨
Thanks for all your hard work 😃
