### ISSUE TITLE
Strava Activities Tutorial feedback

### ISSUE THREAD

**Issue by mdleye** [robiningelbrecht/strava-activities-template#52]
1. [Create a new repository](https://github.com/new?template_name=strava-activities-template&template_owner=robiningelbrecht) using this template
> Create a new repository using this template by clicking [HERE](https://github.com/new?template_name=strava-activities-template&template_owner=robiningelbrecht) and filling the required data

2. Next, navigate to your [Strava API settings page](https://www.strava.com/settings/api). Copy the client ID and client secret

> Specify how or link to external page on how to set up strava API
https://developers.strava.com/docs/getting-started/#:~:text=If%20you%20have%20not%20already,My%20API%20Application%E2%80%9D%20page%20now.

3. Scroll own to:
> Scroll down to:

4. Fill out your birthday and run the workflow
> Fill out your birthday YYYY-MM-DD and run the workflow

5. !!! It's important you wait until a workflow is done, before running another one !!!
> Say this before you instruct user to run a second workflow
Mine are now all in error
HELP

![image](https://github.com/robiningelbrecht/strava-activities-template/assets/149835529/b978d807-62f1-4a86-a68b-c7a4bd724b6d)

**Comment by robiningelbrecht** [comment]
Problem is that the database only gets created when importing the activities for the first time. Updating your birthday tries to write to the database which does nox exist yet. I'll update the workflow tomorrow. I'll let you know what you need to change

**Comment by robiningelbrecht** [comment]
@mdleye Updated and fixed the workflows. These files, unfortunately, cannot be updated automatically (GitHub restrictions).
So you'll need to copy over the contents of https://raw.githubusercontent.com/robiningelbrecht/strava-activities-template/fix-workflows/.github/workflows/update-key-value-store.yml to your own `.github/workflows/update-key-value-store.yml`

Do not forget to update the GIT part to your own name again:
```yml
      - name: Initialize GIT
        run: |
          git config --global user.name 'YOUR_GITHUB_USERNAME'
          git config --global user.email 'YOUR_GITHUB_USERNAME@users.noreply.github.com'
```

If this does the trick, your should do the same for `.github/workflows/update-ftp.yml`: https://raw.githubusercontent.com/robiningelbrecht/strava-activities-template/fix-workflows/.github/workflows/update-ftp.yml

**Comment by mdleye** [comment]
It worked! No I can run the activities workflow?

![image](https://github.com/robiningelbrecht/strava-activities-template/assets/149835529/f55c61e4-ce45-4fb1-ab4b-600d48789275)

![image](https://github.com/robiningelbrecht/strava-activities-template/assets/149835529/0169acea-187f-40b7-bf99-a60626bb5363)

Will you process the other feedback before closing the issue?

**Comment by robiningelbrecht** [comment]
Yup, you can run the activities workflow now. Will take a few hours and will probably not finish today as you have a lot of activities. Remainder of the activities will be imported over the next few days

Will close the issue when all feedback has been processed
